INSERT INTO COZINHA (NOME) VALUES ('Tailandesa');
INSERT INTO COZINHA (NOME) VALUES ('Japonesa');

INSERT INTO restaurante (ID, NOME, TAXA_FRETE, COZINHA_ID) VALUES (1, 'Thai Gourmet', 10, 1);
INSERT INTO restaurante (ID, NOME, TAXA_FRETE, COZINHA_ID) VALUES (2, 'Thai Delivery', 9.50, 1);
INSERT INTO restaurante (ID, NOME, TAXA_FRETE, COZINHA_ID) VALUES (3, 'Tuk Tuk Comida Indiana', 15, 2);
    
INSERT INTO ESTADO (ID, NOME) VALUES (1, 'Minas Gerais');
INSERT INTO ESTADO (ID, NOME) VALUES (2, 'São Paulo');
INSERT INTO ESTADO (ID, NOME) VALUES (3, 'Ceará');

INSERT INTO CIDADE (ID, NOME, ESTADO_ID) VALUES (1, 'Uberlândia', 1);
INSERT INTO CIDADE (ID, NOME, ESTADO_ID) VALUES (2, 'Belo Horizonte', 1);
INSERT INTO CIDADE (ID, NOME, ESTADO_ID) VALUES (3, 'São Paulo', 2);
INSERT INTO CIDADE (ID, NOME, ESTADO_ID) VALUES (4, 'Campinas', 2);
INSERT INTO CIDADE (ID, NOME, ESTADO_ID) VALUES (5, 'Fortaleza', 3);

INSERT INTO FORMA_PAGAMENTO (ID, DESCRICAO) VALUES (1, 'Cartão de crédito');
INSERT INTO FORMA_PAGAMENTO (ID, DESCRICAO) VALUES (2, 'Cartão de débito');
INSERT INTO FORMA_PAGAMENTO (ID, DESCRICAO) VALUES (3, 'Dinheiro');

INSERT INTO PERMISSAO (ID, NOME, DESCRICAO) VALUES (1, 'CONSULTAR_COZINHAS', 'Permite consultar COZINHAs');
INSERT INTO PERMISSAO (ID, NOME, DESCRICAO) VALUES (2, 'EDITAR_COZINHAS', 'Permite editar COZINHAs');
        